### ISSUE TITLE
Assess compatibility with Blacklight 8

### ISSUE THREAD

**Issue by corylown** [sul-dlss/blacklight_maps#63]
blacklight_heatmaps gemspec currently limits to Blacklight 7. We should assess what it would take to make this gem compatible with Blacklight 8 because it blocks us updating exhibits to Blacklight 8.

Seeing this in the exhibits logs:

```
DEPRECATION WARNING: #index_presenter is deprecated; use #document_presenter instead. (called from block (2 levels) in __opt_app_exhibits_exhibits_shared_bundle_ruby_______gems_blacklight_heatmaps_______app_views_catalog_index_heatmaps_jbuilder___188503894793875183_58573260 at /opt/app/exhibits/exhibits/shared/bundle/ruby/3.3.0/gems/blacklight_heatmaps-1.1.0/app/views/catalog/index.heatmaps.jbuilder:6)

```

**Comment by marlo-longley** [comment]
@cbeer -- I believe we can close based on your work in https://github.com/sul-dlss/blacklight_heatmaps/pull/69 ? Thank you.

**Comment by cbeer** [comment]
I don't know if this ticket also included propshaft/importmaps/etc work or doing more than the bare minimum to bump the gemspec?

**Comment by marlo-longley** [comment]
Update: #69 adds the `sprockets` option to the CI builds for BL 8, which allows tests to pass. But there is nothing in the test app generator that accounts for the case of BL 8 -- to build with BL 8 locally, we need to add that option.

In addition, we may want to look at getting off sprockets. This app has no package.json or real JS infrastructure, so more investigation is needed.

**Comment by marlo-longley** [comment]
Work in progress here: https://github.com/sul-dlss/blacklight_heatmaps/pull/70 -- waiting to test its integration with Exhibits, when exhibits is in an upgraded state to do so.
